sudo: false

branches:
  except:
    - gh-pages

notifications:
  email: false

matrix:
  include:
    - language: android
      jdk: oraclejdk8
      env:
        - secure: "SWQBLsaI5fOfiM+48/oAOcynsnpa1hHADxs8Vsmt7gsqVrtL369znwsX+PkNOXTdAROPKHzfCw1PkMSKiWHwSB+Gc8fMqFoVjxPnpi0NAhm2b4q4pq6GLOed2xF93eLoQZ7x4UwcUie58Qlwif9ZSGyp+7V6fEy7/AexGLPAuD0="
        - secure: "gFmZ18DktyZonExeAYGT4HtCodvAbRcH94AImWG6DrJZFzGkRSN//s1AjrgkAL/jZ4lLuoxyCs1nBoX2U83LmpJ8KxLIhU/45JlJgmD1tnE2zdFim6dHN+J6Yj7MCWqD5KO6E0dJickTJG2XzFu0oN3vBn7sETliQHzlw2lw8ME="
      before_install:
        - cd kotlin
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.m2
    - language: swift
      os: osx
      osx_image: xcode10.1
      before_install:
      - gem update --system
      - gem install bundler
      script:
      - bundle exec pod lib lint Workflow.podspec --allow-warnings --verbose
    - language: node_js
      node_js:
        - "stable"
      env:
        - secure: "D5sZCGWbg/wsLAcC+ln+Y7SJL8LWbYyfcHzCKLQr51bMp8U+DCYISuKERO+zKJQkTONhJUtB7ZvH6eo9eUA6q3sj13dtugT+nB4OJBYbfWuHtBPEHse+l/1GkTcy/L2S/52Sb2xWFNOBSVwQclPJ1ZAlhak9LHbFLopXuicMHvPUZwPa3LCu8paSgKKU6KxLcV1XG86pyM9I2W5/PtVRZ4/wMViY6MsHbNmMUFz+EU7EDJOpUCHLz/vlxCBXgpffgn9w5Po3nJGA6q6HjHqDlM594pMu/pGTqG+9vZNb5BHyQx7Fj3IGhh0GJrCp5UJJVLVEqoudGIPsBs7w385K17hUGv16G/w3ZqDfN+p5pIoKzKhNkdqHJ1b78IGeFxSnVacH0I148vrV3Z0CLh9p0Go0jILWPQ1lh2BHzi+30RKm2yTnWHHgU45aFfeSUY6tN9NyImC9xP7mCUZScYy3KANuqc1+FVJQil6IMCskZiLTRLSx92CAORd4YPqxTLwJKiJ0NBpsmLQj1HiNmJqbnd7fJcGWhCCcIQacjviL75J5BUVAJFHwGAQrk1Rzu/G3t2XyNHFGTv5H5c0j3i5Bapr9+he6DTmzAaUwlyjzYCtwF16FzD0kq7v3NDRz31Up0vh8mlVreKs7502zrUXtZhGksQKp4aeu887KUdnC81c="
      cache:
        directories:
          - node_modules
      script:
        - cd docs
        - yarn install
        - yarn test
        - yarn build --prefix-paths
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: public
        target-branch: gh-pages
        on:
          branch: master
